/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author azeldaniel
 */
public class SummerCampForm extends javax.swing.JFrame {
    
    private ArrayList<javax.swing.JCheckBox> acts;
    private ArrayList<Camper> campers;

    /**
     * Creates new form SummerCampForm
     */
    public SummerCampForm() {
        initComponents();
        campers = new ArrayList<>();
        acts = new ArrayList<>();
        acts.add(gamesCheckBox);
        acts.add(tripsCheckBox);
        acts.add(industryCheckBox);
        acts.add(toursCheckBox);
        acts.add(careerCheckBox);
        
        mentorPanel.setVisible(false);
        careerCheckBox.setVisible(false);
        age9_12RadioButton.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ageButtonGroup = new javax.swing.ButtonGroup();
        bannerPanel = new javax.swing.JPanel();
        bannerLabel = new javax.swing.JLabel();
        demographicPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        campTypeLabel = new javax.swing.JLabel();
        campTypeBox = new javax.swing.JComboBox<>();
        ageGroupLabel = new javax.swing.JLabel();
        age9_12RadioButton = new javax.swing.JRadioButton();
        age13_15RadioButton = new javax.swing.JRadioButton();
        activitiesSeparator = new javax.swing.JSeparator();
        activitiesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        toursCheckBox = new javax.swing.JCheckBox();
        gamesCheckBox = new javax.swing.JCheckBox();
        careerCheckBox = new javax.swing.JCheckBox();
        tripsCheckBox = new javax.swing.JCheckBox();
        industryCheckBox = new javax.swing.JCheckBox();
        mentorSeparator = new javax.swing.JSeparator();
        mentorPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        careerGuidanceBox = new javax.swing.JList<>();
        buttonSeparator = new javax.swing.JSeparator();
        buttonPanel = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(420, 425));

        bannerLabel.setIcon(new javax.swing.ImageIcon("/Users/azeldaniel/Desktop/banner.jpg")); // NOI18N

        javax.swing.GroupLayout bannerPanelLayout = new javax.swing.GroupLayout(bannerPanel);
        bannerPanel.setLayout(bannerPanelLayout);
        bannerPanelLayout.setHorizontalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(bannerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bannerPanelLayout.setVerticalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(bannerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        firstNameLabel.setText("First Name");

        lastNameLabel.setText("Last Name");

        campTypeLabel.setText("Camp Type");

        campTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Robotics Camp", "Web Design Camp", "Algorithms Camp" }));
        campTypeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campTypeBoxActionPerformed(evt);
            }
        });

        ageGroupLabel.setText("Age Group");

        ageButtonGroup.add(age9_12RadioButton);
        age9_12RadioButton.setText("9 - 12 years");
        age9_12RadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                age9_12RadioButtonMouseClicked(evt);
            }
        });

        ageButtonGroup.add(age13_15RadioButton);
        age13_15RadioButton.setText("13 - 15 years");
        age13_15RadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                age13_15RadioButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout demographicPanelLayout = new javax.swing.GroupLayout(demographicPanel);
        demographicPanel.setLayout(demographicPanelLayout);
        demographicPanelLayout.setHorizontalGroup(
            demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demographicPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel)
                    .addComponent(lastNameLabel)
                    .addComponent(campTypeLabel)
                    .addComponent(ageGroupLabel))
                .addGap(24, 24, 24)
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(age13_15RadioButton)
                    .addComponent(age9_12RadioButton)
                    .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(firstNameField)
                        .addComponent(lastNameField)
                        .addComponent(campTypeBox, 0, 175, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        demographicPanelLayout.setVerticalGroup(
            demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demographicPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campTypeLabel)
                    .addComponent(campTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(demographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageGroupLabel)
                    .addComponent(age9_12RadioButton))
                .addGap(10, 10, 10)
                .addComponent(age13_15RadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Activities");

        toursCheckBox.setText("Campus Tours");

        gamesCheckBox.setText("Games");

        careerCheckBox.setText("Career Guidance");
        careerCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                careerCheckBoxMouseClicked(evt);
            }
        });

        tripsCheckBox.setText("Field Trips");

        industryCheckBox.setText("Industry Visits");

        javax.swing.GroupLayout activitiesPanelLayout = new javax.swing.GroupLayout(activitiesPanel);
        activitiesPanel.setLayout(activitiesPanelLayout);
        activitiesPanelLayout.setHorizontalGroup(
            activitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activitiesPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(activitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(careerCheckBox)
                    .addGroup(activitiesPanelLayout.createSequentialGroup()
                        .addGroup(activitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gamesCheckBox)
                            .addComponent(toursCheckBox))
                        .addGap(34, 34, 34)
                        .addGroup(activitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(industryCheckBox)
                            .addComponent(tripsCheckBox))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        activitiesPanelLayout.setVerticalGroup(
            activitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(activitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(toursCheckBox)
                    .addComponent(tripsCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(activitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gamesCheckBox)
                    .addComponent(industryCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(careerCheckBox)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel2.setText("Mentors");

        careerGuidanceBox.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Dr Dorian Smith", "Dr. Lisa Rosenberg", "Prof. Garry Mitchel" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(careerGuidanceBox);

        javax.swing.GroupLayout mentorPanelLayout = new javax.swing.GroupLayout(mentorPanel);
        mentorPanel.setLayout(mentorPanelLayout);
        mentorPanelLayout.setHorizontalGroup(
            mentorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mentorPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mentorPanelLayout.setVerticalGroup(
            mentorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mentorPanelLayout.createSequentialGroup()
                .addGroup(mentorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear Form");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(registerButton)
                .addGap(65, 65, 65)
                .addComponent(clearButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(clearButton))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bannerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(demographicPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activitiesSeparator)
                    .addComponent(activitiesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mentorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mentorSeparator)
                            .addComponent(buttonSeparator)
                            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bannerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(demographicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activitiesSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activitiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mentorSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mentorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void age13_15RadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_age13_15RadioButtonMouseClicked
        // TODO add your handling code here:
        careerCheckBox.setVisible(true);
    }//GEN-LAST:event_age13_15RadioButtonMouseClicked

    private void age9_12RadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_age9_12RadioButtonMouseClicked
        // TODO add your handling code here:
        careerCheckBox.setVisible(false);
        mentorPanel.setVisible(false);
    }//GEN-LAST:event_age9_12RadioButtonMouseClicked

    private void careerCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_careerCheckBoxMouseClicked
        // TODO add your handling code here:
        if(careerCheckBox.isSelected())
            mentorPanel.setVisible(true);
        else
            mentorPanel.setVisible(false);
    }//GEN-LAST:event_careerCheckBoxMouseClicked

    private void campTypeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campTypeBoxActionPerformed
        // TODO add your handling code here:
        String campType = campTypeBox.getSelectedItem().toString();
         if(campType.equals("Robotics Camp")){
          careerGuidanceBox.setModel(new javax.swing.AbstractListModel<String>() {
             String[] strings = { "Dr. Dorian Smith", "Dr. Lisa Rosenberg", "Prof. Garry Mitchel"};
             public int getSize() { return strings.length; }
             public String getElementAt(int i) { return strings[i]; }
          });
         }
         if(campType.equals("Web Design Camp")){
          careerGuidanceBox.setModel(new javax.swing.AbstractListModel<String>() {
             String[] strings = { "Dr. James Marsden", "Dr. Sal Shrinavasan" };
             public int getSize() { return strings.length; }
             public String getElementAt(int i) { return strings[i]; }
             });
         }
         if(campType.equals("Algorithms Camp")){
          careerGuidanceBox.setModel(new javax.swing.AbstractListModel<String>() {
             String[] strings = { "Dr. Elliot Beso", "Dr. Welsey Singh", "Prof. Garry Mitchel"};
             public int getSize() { return strings.length; }
             public String getElementAt(int i) { return strings[i]; }
          });
         }
    }//GEN-LAST:event_campTypeBoxActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();
        String campType = campTypeBox.getSelectedItem().toString();
        String ageGroup;
        List<String> activities = new ArrayList<>();
        List<String> mentors = careerGuidanceBox.getSelectedValuesList();
        
        if(age9_12RadioButton.isSelected())
            ageGroup = "9 - 12 years";
        else
            ageGroup = "13 - 15 years";
        
        for(javax.swing.JCheckBox b: acts){
            if(b.isSelected())
                activities.add(b.getText());
        }
        firstNameField.setText("");
        lastNameField.setText("");
        
        Camper camper = new Camper(firstName, lastName, campType);
        camper.setAgeGroup(ageGroup);
        camper.setMentors(mentors);
        camper.setActivities(activities);
        campers.add(camper);
        System.out.println(camper.toString());
    }//GEN-LAST:event_registerButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        age9_12RadioButton.setSelected(true);
        age13_15RadioButton.setSelected(false);
        for(javax.swing.JCheckBox b: acts){
            b.setSelected(false);
        }
        careerCheckBox.setVisible(false);
        mentorPanel.setVisible(false);
        firstNameField.setText("");
        lastNameField.setText("");
        campTypeBox.setSelectedIndex(0);
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SummerCampForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SummerCampForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SummerCampForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SummerCampForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SummerCampForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activitiesPanel;
    private javax.swing.JSeparator activitiesSeparator;
    private javax.swing.JRadioButton age13_15RadioButton;
    private javax.swing.JRadioButton age9_12RadioButton;
    private javax.swing.ButtonGroup ageButtonGroup;
    private javax.swing.JLabel ageGroupLabel;
    private javax.swing.JLabel bannerLabel;
    private javax.swing.JPanel bannerPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JSeparator buttonSeparator;
    private javax.swing.JComboBox<String> campTypeBox;
    private javax.swing.JLabel campTypeLabel;
    private javax.swing.JCheckBox careerCheckBox;
    private javax.swing.JList<String> careerGuidanceBox;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel demographicPanel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JCheckBox gamesCheckBox;
    private javax.swing.JCheckBox industryCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPanel mentorPanel;
    private javax.swing.JSeparator mentorSeparator;
    private javax.swing.JButton registerButton;
    private javax.swing.JCheckBox toursCheckBox;
    private javax.swing.JCheckBox tripsCheckBox;
    // End of variables declaration//GEN-END:variables
}
